#!/bin/sh
# Run dart format
eval "$(dart format lib)"
eval "$(dart fix --apply --code=unnecessary_brace_in_string_interps)"
eval "$(dart fix --apply --code=unused_element_parameter)"
eval "$(dart fix --apply --code=missing_dependency)"
eval "$(dart fix --apply --code=unused_import)"
eval "$(dart fix --apply --code=unnecessary_this)"

# Stage the formatted files
echo "$DART_FILES" | xargs git add

exit 0

